import XCTest
@testable import RoasSensor

/// Byte-for-byte parity with the backend `apps/tracking/security.py`. Expected
/// values were generated by calling `hash_email` / `hash_phone` on the server, so
/// this fails the moment the Swift normalization drifts from the Python one — the
/// exact silent identity-mismatch this guards against. Pure Foundation/CryptoKit,
/// so it runs on macOS without a simulator.
final class HashingParityTests: XCTestCase {

    func testEmailMatchesBackend() {
        XCTAssertEqual(
            Hashing.hashEmail("  Buyer@Example.COM "), // trims + lowercases
            "6a6c26195c3682faa816966af789717c3bfa834eee6c599d667d2b3429c27cfd"
        )
        XCTAssertEqual(
            Hashing.hashEmail("test@roas.dev"),
            "bdb94ffa4890be68a8e80f9eacfbd322bb91fd1b39ceb76bc5213532e8879367"
        )
    }

    func testPhoneMatchesBackend() {
        XCTAssertEqual(
            Hashing.hashPhone("+1 (415) 555-0132"), // → +14155550132
            "9e1919ad78a34fd67a84bfbcf2fea14074065517bea32e92924771c3f92e5462"
        )
    }

    func testArabicIndicDigitsFoldToTheSameHashAsASCII() {
        // A phone typed on a non-Latin keypad must hash identically, or the
        // identity bridge silently fails. U+0660–0669 → ASCII 0–9.
        let arabic = "٠٥٠١٢٣٤٥٦٧" // 0501234567
        XCTAssertEqual(Hashing.hashPhone(arabic), Hashing.hashPhone("0501234567"))
        XCTAssertEqual(
            Hashing.hashPhone(arabic),
            "01cc498c268a4314d231f2e899a9faf717b7f8bbc9f3889bb1e539651907adde"
        )
    }

    func testTooShortPhoneIsNotAKey() {
        XCTAssertEqual(Hashing.hashPhone("123"), "") // < 7 digits → empty
    }
}
